"""
A Person
"""
type Person {
  id: ID!
  name: String! @format
  interests: Interests
  friends: [Person]!
}

"""
Interests track
"""
type Interests {
  hiking: [Hike]!
  concert: [Concert]!
  watchList: [TVShow]!
}

type Hike {
  id: ID!
  place: String!
  summary: String @match @format
}

type Concert {
  id: ID!
  artist: String!
  local: String @format
}

type TVShow {
  id: ID!
  title: String @format
  provider: Provider
}